spring:
  profiles.active: dev
server.port: 1210
artifact:
  id : store
  version: 0.0.1-SNAPSHOT
environment:
  nodeName :
---
spring:
  profiles: dev
mongodb:
  host: localhost
  port: 27017
  database: store_db
  username: 
  password: 
  authenticationDB: 